Publero\TemplateMailerBundle\Model\Template:
    type: document
    collection: publero_template_mailer_template
    fields:
        id:
            id: true
        code:
            type: string
            unique:
                order: desc
        hash:
            type: string
            unique:
                order: desc
        sender:
            type: string
        subject:
            type: string
        body:
            type: string
        defaultParams:
            type: hash
        checksum:
            type: string
