Publero\TemplateMailerBundle\Model\Template:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            unique: true
        hash:
            type: string
            unique: true
            nullable: true
        sender:
            type: text
        subject:
            type: text
        body:
            type: text
        defaultParams:
            type: json_array
        checksum:
            type: string
            nullable: true
